language: python

python:
  - "3.4"
  - "3.5"

install:
    - pip install -r requirements.txt

script: make test

services: redis

notifications:
    email:
        on_success: change
        on_failure: change
